### ISSUE TITLE
Add support for custom protoc java plugin arguments

### ISSUE THREAD

**Issue by efenglu** [xolstice/protobuf-maven-plugin#56]
**Is your feature request related to a problem? Please describe.**
There are features of the java plugin that are not exposed as .proto options. I was like to be able to use them

**Describe the solution you'd like**
The custom plugin execution already supports this.  Simply add the element:
```<pluginParameter>```

**Describe alternatives you've considered**
Adding a custom option to proto would require changes to the proto syntax.

**Comment by sergei-ivanov** [comment]
Can you please point me to the examples/documentation of additional parameters for java plugin?

**Comment by marcoferrer** [comment]
I author a plugin that’s affected by this. Details documented in this issue, including an example configuration https://github.com/marcoferrer/kroto-plus/issues/28

**Comment by sergei-ivanov** [comment]
@marcoferrer thanks for describing the use case, it's exactly what I was looking for. I think your case is further complicated by the fact (correct me if I am wrong) that your plugin is not standalone, but rather works alongside Java plugin to inject extra code into the generated classes.

While I still have a long term plan to refactor `protobuf-maven-plugin` configuration in a similar way to how gradle plugin works (multiple outputs, single execution), it is not something I am planning for the nearest future. 

What I can do though is to push the optional plugin parameter into the base class, so that all plugin outputs can use it. The next release will be full of breaking changes, so it's probably a good time to roll this change in as well.

**Comment by efenglu** [comment]
This will work for me.  I was also experimenting with the other Google Java protoc command line arguments, like adding @generated to class files.  

I also am developing a plug-in that I would like to control the behavior of from the pom file and not the proto file.

**Comment by marcoferrer** [comment]
@sergei-ivanov An issue I saw in the gradle plugin repo reminded me of this issue. I remember you mentioned that you had plans to refactor this plugin to use a single protoc invocation. It looks like that might cause a breaking change for existing maven users. Details outlined [here](https://github.com/google/protobuf-gradle-plugin/issues/306)

Just wanted to give a heads up

**Comment by sergei-ivanov** [comment]
I concur with @ejona86: the case described in google/protobuf-gradle-plugin#306 looks more like an abuse of a legacy feature than a genuine problem. Having two identically named protobuf messages in the same protobuf namespace is definitely an invalid case, and `protoc` is entirely correct to complain about it.

**Comment by marcoferrer** [comment]
I agree. It would be worth noting in the release of the refactor that users experiencing compilation errors need to review their proto definitions for duplicate message names.

**Comment by thesamet** [comment]
I would also be interested to see `pluginParameter` being supported for custom java plugins. I am the author of [ScalaPB](https://scalapb.github.io/) which includes a protobuf plugin that generates Scala code and is written in Scala. The plugin supports [multiple options](https://scalapb.github.io/scalapbc.html#passing-generator-parameters) that users can pass through protoc. We recommend using this plugin for maven users, and they frequently need to pass additional options and we're hitting this limitation. See for example: https://gitter.im/ScalaPB/community?at=5ddf7d50d64a052fb67918c9

**Comment by jeffzoch** [comment]
Any progress on this? Not sure if its being actively worked on but the 0.7 release has been on hold for a year or so>?

**Comment by artie-shevchenko** [comment]
+1, upvote

**Comment by sahendrickson** [comment]
I'd like to have the ability to include the --fatal_warnings argument.

**Comment by sergei-ivanov** [comment]
> [!IMPORTANT]
> This project is no longer being maintained, and no further contributions will be considered.
> 
> Please consider switching to alternatives, such as: \
> https://github.com/ascopes/protobuf-maven-plugin
